version: "3.9"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN:?CF_TUNNEL_TOKEN is required}
    restart: unless-stopped
    depends_on: [app]
    networks: [preprod]

networks:
  preprod:
    driver: bridge
